<?php
	declare(strict_types=1);
	/** @var FreshRSS_View $this */
	$topline_read = FreshRSS_Context::userConf()->topline_read;
	$topline_favorite = FreshRSS_Context::userConf()->topline_favorite;
	$topline_website = FreshRSS_Context::userConf()->topline_website;
	$topline_thumbnail = FreshRSS_Context::userConf()->topline_thumbnail;
	$topline_summary = FreshRSS_Context::userConf()->topline_summary;
	$topline_display_authors = FreshRSS_Context::userConf()->topline_display_authors;
	$topline_date = FreshRSS_Context::userConf()->topline_date;
	$topline_link = FreshRSS_Context::userConf()->topline_link;
	$lazyload = FreshRSS_Context::userConf()->lazyload;

	// setup for favicon sprites
	$favicons_DIR = DATA_PATH . '/favicons/';
	if (file_exists($favicons_DIR . "favicons.json")) {
		$str = file_get_contents($favicons_DIR . "favicons.json");
		$oldFavicons = json_decode($str, true);
	} else {
		$oldFavicons = [];
	}

	?><ul class="horizontal-list flux_header website<?= $topline_website ?>"><?php

	if ($topline_website !== 'none'):
	?><li class="item website <?= $topline_website ?>">
		<a href="<?= _url('index', 'index', 'get', 'f_' . $this->feed->id()) ?>" class="item-element" title="<?= _t('gen.action.filter') ?>: <?= $this->feed->name() ?>">
			<?php
			// Add hash ID always, but only set blank src if feed in sprite
			if ('name' !== $topline_website) {
				$this_hash = $this->feed->hash();
				if (isset($oldFavicons[$this_hash]) && $oldFavicons[$this_hash]['feed_favicon'] >= 0 ) {
					?><img class="favicon" id="<?= $this_hash ?>" src="../themes/icons/transparent.png" loading="lazy" /><?php
				} else {
					?><img class="favicon" id="<?= $this_hash ?>" src="<?= $this->feed->favicon() ?>" alt="✇" loading="lazy" /><?php
				}
			}
			if ('icon' !== $topline_website): ?><span class="websiteName"><?= $this->feed->name() ?></span><?php endif; ?>
		</a>
		</li><?php
	endif; ?>

	<?php
	if ($topline_thumbnail !== 'none'):
	?><li class="item thumbnail <?= $topline_thumbnail ?> <?= $topline_summary ? '' : 'small' ?>"><?php
		$thumbnail = $this->entry->thumbnail();
		if ($thumbnail != null):
			?><img src="<?= $thumbnail['url'] ?>" class="item-element "<?= $lazyload ? ' loading="lazy"' : '' ?> alt="" /><?php
		endif;
	?></li><?php
	endif; ?>
	<li class="item titleAuthorSummaryDate">
		<a target="_blank" rel="noreferrer" href="<?= $this->entry->link() ?>" class="item-element title<?= (($topline_thumbnail !== 'none') || $topline_summary) ? ' multiline' : '' ?>" dir="auto"><?= $this->entry->title() ?><?php
		if ($topline_display_authors):
			?><span class="author"><?php
			$authors = $this->entry->authors();
			if (is_array($authors)) {
				$first = true;
				foreach ($authors as $author) {
					echo $first ? $author : ', ' . $author;
					$first = false;
				}
			}
			?></span><?php
		endif;
		?></a>
	<?php
	if ($topline_summary):
		?><div class="summary"><?= trim(mb_substr(strip_tags($this->entry->content(false)), 0, 500, 'UTF-8')) ?></div><?php
	endif; ?>
	<?php if ($topline_date) { ?><span class="item-element date"><time datetime="<?= $this->entry->machineReadableDate() ?>"><?= $this->entry->date() ?></time>&nbsp;</span><?php } ?>
	</li>
	<?php if ($topline_link) { ?><li class="item link"><a target="_blank" rel="noreferrer" href="<?= $this->entry->link() ?>" class="item-element" title="<?=
		_t('conf.shortcut.see_on_website') ?>"><?= _i('link') ?></a></li><?php } ?>
	
	<?php if (FreshRSS_Auth::hasAccess()) {
		if ($topline_read) {
			?><li class="item manage"><?php
				$arUrl = array('c' => 'entry', 'a' => 'read', 'params' => array('id' => $this->entry->id()));
				if ($this->entry->isRead()) {
					$arUrl['params']['is_read'] = 0;
				}
				?><a class="item-element read" href="<?= Minz_Url::display($arUrl) ?>" title="<?= _t('conf.shortcut.mark_read') ?>"><?php
					echo _i($this->entry->isRead() ? 'read' : 'unread'); ?></a><?php
			?></li><?php
		}
		if ($topline_favorite) {
			?><li class="item manage"><?php
				$arUrl = array('c' => 'entry', 'a' => 'bookmark', 'params' => array('id' => $this->entry->id()));
				if ($this->entry->isFavorite()) {
					$arUrl['params']['is_favorite'] = 0;
				}
				?><a class="item-element bookmark" href="<?= Minz_Url::display($arUrl) ?>" title="<?= _t('conf.shortcut.mark_favorite') ?>"><?php
					echo _i($this->entry->isFavorite() ? 'starred' : 'non-starred'); ?></a><?php
			?></li><?php
		}
	}
	?>
</ul>
